version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/projetos/financeiro-app/ 
permissions:
  - object: /home/ec2-user/projetos/financeiro-app/scripts
    pattern: "**"            
    mode: 775     
    type:
      - file
hooks:  
  AfterInstall:
    - location: /home/ec2-user/projetos/financeiro-app/scripts/deploy-financeiro-app.sh      
  ApplicationStart:
    - location: /home/ec2-user/projetos/financeiro-app/scripts/restart-nginx.sh
      timeout: 3600
