version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/projetos/financeiro-app/ 
hooks:  
  AfterInstall:
    - location: scripts/deploy-financeiro-app.sh      
  ApplicationStart:
    - location: scripts/restart-nginx.sh
      timeout: 3600
